version: '3.8'
services:
  api01:
    container_name: api01
    image: ./api
    ports:
      - "3000:3000"
  api02:
    container_name: api02
    image: ./api
    environment:
      - MESSAGE= "Jhosep Narvaez"
    ports:
      - "3001:3000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase